//
// Created by Bhavishya Sharma on 27/09/20.
//

#ifndef IITH_LAB_QTYPE_H
#define IITH_LAB_QTYPE_H

#include <map>
#include <string>
#include <sys/types.h>

enum QType {
    QT_A = 1,
    QT_NS,
    QT_MD,
    QT_MF,
    QT_CNAME,
    QT_SOA,
    QT_MB,
    QT_MG,
    QT_MR,
    QT_NULL,
    QT_WKS,
    QT_PTR,
    QT_HINFO,
    QT_MINFO,
    QT_MX,
    QT_TXT,
    QT_RP,
    QT_AFSDB,
    QT_SIG = 24,
    QT_KEY,
    QT_AAAA = 28,
    QT_LOC,
    QT_SRV = 33,
    QT_NAPTR = 35,
    QT_KX,
    QT_CERT,
    QT_DNAME = 39,
    QT_OPT = 41,
    QT_APL,
    QT_DS,
    QT_SSHFP,
    QT_IPSECKEY,
    QT_RRSIG,
    QT_NSEC,
    QT_DNSKEY,
    QT_DHCID,
    QT_NSEC3,
    QT_NSEC3PARAM,
    QT_TLSA,
    QT_SMIMEA,
    QT_HIP = 55,
    QT_CDS = 59,
    QT_CDNSKEY,
    QT_OPENPGPKEY,
    QT_CSYNC,
    QT_ZONEMD,
    QT_SVCB,
    QT_HTTPS,
    QT_EUI48 = 108,
    QT_EUI64,
    QT_TKEY = 249,
    QT_TSIG,
    QT_IXFR,
    QT_AXFR,
    QT_MAILB,
    QT_MAILA,
    QT_ANY,
    QT_URI,
    QT_CAA,
    QT_TA = 32768,
    QT_DLV
};

static std::map<u_int16_t, std::string> qTypeMap = {{1, "A"}, {2, "NS"}, {3, "MD"}, {4, "MF"},
                                                    {5, "CNAME"}, {6, "SOA"}, {7, "MB"}, {8, "MG"},
                                                    {9, "MR"}, {10, "NULL"}, {11, "WKS"}, {12, "PTR"},
                                                    {13, "HINFO"}, {14, "MINFO"}, {15, "MX"}, {16, "TXT"},
                                                    {17, "RP"}, {18, "AFSDB"}, {24, "SIG"}, {25, "KEY"},
                                                    {28, "AAAA"}, {29, "LOC"}, {33, "SRV"}, {35, "NAPTR"},
                                                    {36, "KX"}, {37, "CERT"}, {39, "DNAME"}, {41, "OPT"},
                                                    {42, "APL"}, {43, "DS"}, {44, "SSHFP"}, {45, "IPSECKEY"},
                                                    {46, "RRSIG"}, {47, "NSEC"}, {48, "DNSKEY"}, {49, "DHCID"},
                                                    {50, "NSEC3"}, {51, "TLSA"}, {52, "SMIMEA"}, {55, "HIP"},
                                                    {59, "CDS"}, {60, "CDNSKEY"}, {61, "OPENPGPKEY"}, {62, "CSYNC"},
                                                    {63, "ZONEMD"}, {64, "SVCB"}, {65, "HTTPS"}, {108, "EUI48"},
                                                    {109, "EUI64"}, {249, "TKEY"}, {250, "TSIG"}, {251, "IXFR"},
                                                    {252, "AXFR"}, {253, "MAILB"}, {254, "MAILA"}, {255, "ANY"},
                                                    {256, "URI"},{257, "CAA"}, {32768, "TA"}, {32769, "DLV"}};

static std::map<std::string, u_int16_t> qTypeReverseMap = {{"A", 1}, {"NS", 2}, {"MD", 3}, {"MF", 4},
                                                           {"CNAME", 5}, {"SOA", 6}, {"MB", 7}, {"MG", 8},
                                                           {"MR", 9}, {"NULL", 10}, {"WKS", 11}, {"PTR", 12},
                                                           {"HINFO", 13}, {"MINFO", 14}, {"MX", 15}, {"TXT", 16},
                                                           {"RP", 17}, {"AFSDB", 18}, {"SIG", 24}, {"KEY", 25},
                                                           {"AAAA", 28}, {"LOC", 29}, {"SRV", 33}, {"NAPTR", 35},
                                                           {"KX", 36}, {"CERT", 37}, {"DNAME", 39}, {"OPT", 41},
                                                           {"APL", 42}, {"DS", 43}, {"SSHFP", 44}, {"IPSECKEY", 45},
                                                           {"RRSIG", 46}, {"NSEC", 47}, {"DNSKEY", 48}, {"DHCID", 49},
                                                           {"NSEC3", 50}, {"TLSA", 51}, {"SMIMEA", 52}, {"HIP", 55},
                                                           {"CDS", 59}, {"CDNSKEY", 60}, {"OPENPGPKEY", 61}, {"CSYNC", 62},
                                                           {"ZONEMD", 63}, {"SVCB", 64}, {"HTTPS", 65}, {"EUI48", 108},
                                                           {"EUI64", 109}, {"TKEY", 249}, {"TSIG", 250}, {"IXFR", 251},
                                                           {"AXFR", 252}, {"MAILB", 253}, {"MAILA", 254}, {"ANY", 255},
                                                           {"URI", 256}, {"CAA", 257}, {"TA", 32768},  {"DLV", 32769}};

#endif //IITH_LAB_QTYPE_H
